# Generated by Django 2.1.15 on 2020-05-16 19:59

import articles.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, storage=articles.storage.CustomS3Boto3Storage(), upload_to='images'),
        ),
    ]
