# Generated by Django 3.0.5 on 2020-04-28 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_liked_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='liked_user',
            new_name='liked_users',
        ),
    ]
