# Generated by Django 3.0.5 on 2020-04-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200428_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='article',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='articles.Hashtag'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='tag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
