# Generated by Django 3.0.5 on 2020-04-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200428_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='hashtag',
            old_name='tag',
            new_name='name',
        ),
    ]
